version: '2'
services:
  elasticsearch:
    build: elasticsearch/
    #image: elasticsearch:5.2.0
    container_name: elasticsearch
    #command: elasticsearch -Des.cluster.name: docker-cluster
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS: -Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
   # mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/es:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"
    networks:
      - esnet
  
  elasticsearchx:
    build: elasticsearchx/
    #image: elasticsearch:5.2.0
    container_name: elasticsearchx
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65636
  #  mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/es2:/usr/share/elasticsearch/data
    ports:
      - "9300"
      - "9200"
    networks:
      - esnet
  
  logstash:
    build: logstash/
   # image: logstash:5.2.0
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - esnet
    depends_on:
      - elasticsearch
      - elasticsearchx

  kibana:
    build: kibana/
    #image: docker.elastic.co/kibana/kibana:5.2.0
    environment:
     ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ./kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch
      - elasticsearchx

#volumes:
#  esdata1:
#    driver: local
#  esdata2:
#    driver: local

networks:
  esnet:
    driver: bridge
