version: '3'

services:
  master:
    image: itzg/elasticsearch
    environment:
      TYPE: MASTER
      UNICAST_HOSTS: master
      MIN_MASTERS: 1
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
  data:
    image: itzg/elasticsearch
    environment:
      TYPE: DATA
      UNICAST_HOSTS: master
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 60s
  gateway:
    image: itzg/elasticsearch
    ports:
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    environment:
      TYPE: GATEWAY
      UNICAST_HOSTS: master
  kibana:
    image: kibana
    ports:
      - "5601:5601/tcp"
    environment:
      ELASTICSEARCH_URL: http://gateway:9200
