version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.2.0
    ports:
      - "9300:9300"
      - "9200:9200"
  
  logstash:
    image: logstash:5.2.0
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"

  kibana:
    image: kibana:5.2.0
    environment:
     ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
